language: cpp
sudo: required
compiler: gcc
os: linux
dist: xenial
env: targetFile=min releaseName=min_ubuntu_xenial_x64
cache:
  bundler: true
  apt: true
  directories:
    - /opt/qt*/
    - ~/Documents/nfd/ndn-cxx
group: deprecated-2019Q1
before_install:
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -y
  - sudo apt-get update
  - sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libavdevice-dev
    libavutil-dev
  - sudo apt install libsdl2-dev libsdl2-image-dev
  - sudo add-apt-repository ppa:beineri/opt-qt-5.7.1-xenial -y; sudo apt-get update
    -qq; sudo apt-get install -y libglew-dev libglfw3-dev; sudo apt-get install -y qt512-meta-minimal;
  - sudo apt install qt57multimedia
  - sudo apt install libpcap-dev libboost-all-dev
  - git clone https://github.com/SunnyQjm/NDNInstaller.git
  - cd NDNInstaller
  - ./install_ndn-cxx.sh
  - cd ..
before_script: source /opt/qt512/bin/qt512-env.sh;
script:
  - qmake
  - make
before_deploy:
  - wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
  - mv linuxdeployqt-6-x86_64.AppImage linuxdeployqt
  - chmod a+x linuxdeployqt
  - ./linuxdeployqt MIN.desktop -appimage
  - mv Min-*.AppImage ${releaseName}.AppImage
deploy:
  provider: releases
  api_key:
    secure: 10+MQsEnsdaO3J75kn2JqIBEK65WTNmnvEraOtNoC3kXfgl8a0p9KMRWkzTlQrrrAzgqFp6Lf8qYkq3Xdg/hV0Se89s9LmNozzPMbpuR1mDAugDyKoJjjv/HMJQgYbzSHLb7mKcEYKcrldW4n8wilYTo1LnXZQCwgXT4mIjGzs73q9q95+C8W/ERlOQnm89r5laQ7YVafAsYjFaw1VSUZ7llwJrShGTsETOqiF198QboY/Q8RvNh8WUYHlbrq/eraXIYql/XBeREyXE4WPcJs9EuKQTET0dq7DXFoOaI3EMcIqSCjlLbNLdeDIZEH2CgVzcz+FmA1+xolA2NRtrqAEvlfRrJJ8EDVK6ONFRBJKygd5ikv5EvuZZxIs6/Xi9X322QOOQrReihF+rNQS8cq9SBpFdZrBS4JXm8NF1XwGFvxc8Coz4NAac+35viy7a6wDIu/1exn3A4HhRaGj5Aj9yUoKOsU++m3a6cv2WY+BpA/fhCTu1JGZJlsTJrmmsV0/MhaYnnrkKtuGcjv+NKKLdYYMtMxZvlGjOnZ8vpHXN/yo3JRmWr9VvJIomrRKfMnOD/OuBz5KzwdMCvgXiHL+x07Kk/AEjyCewfT4ZFc1jSQOKmVMBZp3w03n6mGXG68rNSVuaTw0A3A41cuqxrW2Om9xVuSF5kcnowOSOUt5U=
  skip_cleanup: true
  file: ${releaseName}.AppImage
  on:
    repo: SunnyQjm/MIN
#    tags: true
