language: cpp
sudo: required
compiler: gcc
os: linux
dist: xenial
env: targetFile=min releaseName=min_ubuntu_xenial_x64
cache:
  bundler: true
  apt: true
  directories:
    - /opt/qt*/
    - ~/Documents/nfd/ndn-cxx
group: deprecated-2019Q1
before_install:
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -y
  - sudo apt-get update
  - sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libavdevice-dev
    libavutil-dev
  - sudo apt install libsdl2-dev libsdl2-image-dev
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y; sudo apt-get update
    -qq; sudo apt-get install -y libglew-dev libglfw3-dev; sudo apt-get install -y qt512-meta-minimal;
  - sudo apt install qt512multimedia
  - sudo apt install libpcap-dev libboost-all-dev
  - git clone https://github.com/SunnyQjm/NDNInstaller.git
  - cd NDNInstaller
  - ./install_ndn-cxx.sh
  - cd ..
before_script: source /opt/qt512/bin/qt512-env.sh;
script:
  - qmake
  - make
before_deploy:
  - wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
  - mv linuxdeployqt-6-x86_64.AppImage linuxdeployqt
  - chmod a+x linuxdeployqt
  - ./linuxdeployqt MIN.desktop -appimage
  - mv Min-*.AppImage ${releaseName}.AppImage
deploy:
  provider: releases
  api_key:
    secure: NgWS+KzlIHt0od1/rxL1PzLIr9CWVxUAMjw8jlZt889vhVCHhJ1bnmfkBVrm/MZRLi/GSD+5S3l9Ot1JoRVx4eAavXgt3QVK05KrqvKrFe2P+ytI7yo8Ab+PiTDOgnlOQfRzALW9YqwaEPN0OALmV0hu/q0m0J92U8DSiVgyFTH/5coBs364ijog0a09PSx10CF6T/q8NS9tJaOz13i2NbokX6Q/H3BmP3jbt94gLfmsyYu/7pjdz3q1h/ai54uXYOn83tXqII/Kzd8D4QXpMpivC1Ow5GkL2NDBBd60C38zP9m5wyKkZDkk5juKpM7oOWpyxrKnPqm5aYqX/DIbSiTZ7zNWO4dtLuj1DzoVdiByo8vRJkLBulTuOt6jCFlmzEEexbe+9xRrB8CWCGNUPnmyBCHfPm/beuuqWHN2Agfe03FjvgixVzGcH8gnUldncFKjFu88sOuCQrHGC5ADEW2ehKOTmR9UX6kYK73RI3PDBckRRHI29g1ZFLvGB/5/9HEkd4ILmX1JeQyKy3W3rFcs5yD2Y4qiD3KmA0T64lAeEkoV/xs7VN94GDKZCdl3wtD5a/9XcljuiKeXRr2n3Gn1IYE4JhYaKSmkpSr6yfuZFXRVI8cfd1VaPf4Rs+u8d853+RevVGZNGse0ngLiKyfypnsqzTFlTwO16l5oFDw=
  file: ${releaseName}.AppImage
  on:
    repo: SunnyQjm/MIN
