language: cpp
sudo: required
compiler: g++
os: linux
dist: xenial
env: targetFile=min releaseName=min_ubuntu_xenial_x64
cache:
  bundler: true
  apt: true
  directories:
    - "/opt/qt*/"
    - "~/Documents/nfd/ndn-cxx"
group: deprecated-2019Q1
before_install:
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -y
  - sudo apt-get update
  - sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libavdevice-dev
    libavutil-dev
  - sudo apt install libsdl2-dev libsdl2-image-dev
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y; sudo apt-get update
    -qq; sudo apt-get install -y libglew-dev libglfw3-dev; sudo apt-get install -y qt512-meta-minimal;
  - sudo apt install qt512multimedia
  - sudo apt install libpcap-dev libboost-all-dev
  - git clone https://github.com/SunnyQjm/NDNInstaller.git
  - cd NDNInstaller
  - "./install_ndn-cxx.sh"
  - cd ..
before_script: source /opt/qt512/bin/qt512-env.sh;
script:
  - qmake
  - make
before_deploy:
  - wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
  - mv linuxdeployqt-6-x86_64.AppImage linuxdeployqt
  - chmod +x linuxdeployqt
  - mkdir ${releaseName}
  - mv min ${releaseName}/t
  - cd ${releaseName}
  - "../linuxdeployqt min -appimage"
  - cd ..
  - tar -czf ${releaseName}.tar.gz ${releaseName}
deploy:
  provider: releases
  api_key:
    secure: 0wxLba/yumluSyzL/8b4lTFv+y0dbwT0qotgAm+5af+DI76QSQAOrAJXIxQufs3B88aLRMPmq9p91Tko+zEVKZT/BUOUg3m68jM6RjjLsLiysqeJGvOIY8SMnWqS+5TZm66VRAxLKLA1l+G7PMKtp57Sv9QvjUFKc6JoKvBjH0krgTw8Dv1oZ4P9GvakqVfqmCiHL/U/z7AoOBdwPW2FMbIKFr8FjagAbtK1np6qD1MOYcaU3a97oDAGZYEfyMq/AmPi5xNxUs+EftqlZS4Syf4z5vqoKhjjN5QH0/bB9r2CefagYb/Ix/6CCwxyk8WX15y+34buRilBDcrIr48nZUizlEoyWutzV3jBw8JSbsZIp82q6YncTX3dSy3lrkxt1Rpdp1hbkDRGX1lYsWiGm2QElr6H6ybRBN2o/FcY8SkLTcd+LtiCVlc/59BzgXnu3r4ysPW6mC5aFXKewO0wIqZjyqPeVvYsaWrgNV7hYgfmJfUdztnNRvE0krrEnSAvYJuldzbXeyhyqf0KonWJEoDE8QaZugro6llKfyV41Ugev4rsXpLIHYMxyrmYusLhl17gw2ioTrYOdNwBxs+ZPGnAA3HlVt2aeIpIOUL8R5yFlFyjkmzQn56mqlmebTOFdC3ipSJMgMaN201aL4vLCC3SicP6mIckgkLuBbkZaMA=
  file: min_ubuntu_xenial_x64.tar.gz
  on:
    repo: SunnyQjm/MIN
